scoreboard objectives add fuel dummy Fuel
scoreboard players add @s fuel 1

execute @s[scores={fuel=4}] ~~~ title @s actionbar §a§lFuel§r: 100%
execute @s[scores={fuel=8}] ~~~ title @s actionbar §a§lFuel§r: 99%
execute @s[scores={fuel=12}] ~~~ title @s actionbar §a§lFuel§r: 98%
execute @s[scores={fuel=16}] ~~~ title @s actionbar §a§lFuel§r: 97%
execute @s[scores={fuel=20}] ~~~ title @s actionbar §a§lFuel§r: 96%
execute @s[scores={fuel=24}] ~~~ title @s actionbar §a§lFuel§r: 95%
execute @s[scores={fuel=28}] ~~~ title @s actionbar §a§lFuel§r: 94%
execute @s[scores={fuel=32}] ~~~ title @s actionbar §a§lFuel§r: 93%
execute @s[scores={fuel=36}] ~~~ title @s actionbar §a§lFuel§r: 92%
execute @s[scores={fuel=40}] ~~~ title @s actionbar §a§lFuel§r: 91%
execute @s[scores={fuel=44}] ~~~ title @s actionbar §a§lFuel§r: 90%
execute @s[scores={fuel=48}] ~~~ title @s actionbar §a§lFuel§r: 89%
execute @s[scores={fuel=52}] ~~~ title @s actionbar §a§lFuel§r: 88%
execute @s[scores={fuel=56}] ~~~ title @s actionbar §a§lFuel§r: 87%
execute @s[scores={fuel=60}] ~~~ title @s actionbar §a§lFuel§r: 86%
execute @s[scores={fuel=64}] ~~~ title @s actionbar §a§lFuel§r: 85%
execute @s[scores={fuel=68}] ~~~ title @s actionbar §a§lFuel§r: 84%
execute @s[scores={fuel=72}] ~~~ title @s actionbar §a§lFuel§r: 83%
execute @s[scores={fuel=76}] ~~~ title @s actionbar §a§lFuel§r: 82%
execute @s[scores={fuel=80}] ~~~ title @s actionbar §a§lFuel§r: 81%
execute @s[scores={fuel=84}] ~~~ title @s actionbar §a§lFuel§r: 80%
execute @s[scores={fuel=88}] ~~~ title @s actionbar §a§lFuel§r: 79%
execute @s[scores={fuel=92}] ~~~ title @s actionbar §a§lFuel§r: 78%
execute @s[scores={fuel=96}] ~~~ title @s actionbar §a§lFuel§r: 77%
execute @s[scores={fuel=100}] ~~~ title @s actionbar §a§lFuel§r: 76%
execute @s[scores={fuel=104}] ~~~ title @s actionbar §a§lFuel§r: 75%
execute @s[scores={fuel=108}] ~~~ title @s actionbar §a§lFuel§r: 74%
execute @s[scores={fuel=112}] ~~~ title @s actionbar §a§lFuel§r: 73%
execute @s[scores={fuel=116}] ~~~ title @s actionbar §a§lFuel§r: 72%
execute @s[scores={fuel=120}] ~~~ title @s actionbar §a§lFuel§r: 71%
execute @s[scores={fuel=124}] ~~~ title @s actionbar §a§lFuel§r: 70%
execute @s[scores={fuel=128}] ~~~ title @s actionbar §a§lFuel§r: 69%
execute @s[scores={fuel=132}] ~~~ title @s actionbar §a§lFuel§r: 68%
execute @s[scores={fuel=136}] ~~~ title @s actionbar §a§lFuel§r: 67%
execute @s[scores={fuel=140}] ~~~ title @s actionbar §a§lFuel§r: 66%
execute @s[scores={fuel=144}] ~~~ title @s actionbar §a§lFuel§r: 65%
execute @s[scores={fuel=148}] ~~~ title @s actionbar §a§lFuel§r: 64%
execute @s[scores={fuel=152}] ~~~ title @s actionbar §a§lFuel§r: 63%
execute @s[scores={fuel=156}] ~~~ title @s actionbar §a§lFuel§r: 62%
execute @s[scores={fuel=160}] ~~~ title @s actionbar §a§lFuel§r: 61%
execute @s[scores={fuel=164}] ~~~ title @s actionbar §a§lFuel§r: 60%
execute @s[scores={fuel=168}] ~~~ title @s actionbar §a§lFuel§r: 59%
execute @s[scores={fuel=172}] ~~~ title @s actionbar §a§lFuel§r: 58%
execute @s[scores={fuel=176}] ~~~ title @s actionbar §a§lFuel§r: 57%
execute @s[scores={fuel=180}] ~~~ title @s actionbar §a§lFuel§r: 56%
execute @s[scores={fuel=184}] ~~~ title @s actionbar §a§lFuel§r: 55%
execute @s[scores={fuel=188}] ~~~ title @s actionbar §a§lFuel§r: 54%
execute @s[scores={fuel=192}] ~~~ title @s actionbar §a§lFuel§r: 53%
execute @s[scores={fuel=196}] ~~~ title @s actionbar §a§lFuel§r: 52%
execute @s[scores={fuel=200}] ~~~ title @s actionbar §a§lFuel§r: 51%
execute @s[scores={fuel=204}] ~~~ title @s actionbar §a§lFuel§r: 50%
execute @s[scores={fuel=208}] ~~~ title @s actionbar §a§lFuel§r: 49%
execute @s[scores={fuel=212}] ~~~ title @s actionbar §a§lFuel§r: 48%
execute @s[scores={fuel=216}] ~~~ title @s actionbar §a§lFuel§r: 47%
execute @s[scores={fuel=220}] ~~~ title @s actionbar §a§lFuel§r: 46%
execute @s[scores={fuel=224}] ~~~ title @s actionbar §a§lFuel§r: 45%
execute @s[scores={fuel=228}] ~~~ title @s actionbar §a§lFuel§r: 44%
execute @s[scores={fuel=232}] ~~~ title @s actionbar §a§lFuel§r: 43%
execute @s[scores={fuel=236}] ~~~ title @s actionbar §a§lFuel§r: 42%
execute @s[scores={fuel=240}] ~~~ title @s actionbar §a§lFuel§r: 41%
execute @s[scores={fuel=244}] ~~~ title @s actionbar §a§lFuel§r: 40%
execute @s[scores={fuel=248}] ~~~ title @s actionbar §a§lFuel§r: 39%
execute @s[scores={fuel=252}] ~~~ title @s actionbar §a§lFuel§r: 38%
execute @s[scores={fuel=256}] ~~~ title @s actionbar §a§lFuel§r: 37%
execute @s[scores={fuel=260}] ~~~ title @s actionbar §a§lFuel§r: 36%
execute @s[scores={fuel=264}] ~~~ title @s actionbar §a§lFuel§r: 35%
execute @s[scores={fuel=268}] ~~~ title @s actionbar §a§lFuel§r: 34%
execute @s[scores={fuel=272}] ~~~ title @s actionbar §a§lFuel§r: 33%
execute @s[scores={fuel=276}] ~~~ title @s actionbar §a§lFuel§r: 32%
execute @s[scores={fuel=280}] ~~~ title @s actionbar §a§lFuel§r: 31%
execute @s[scores={fuel=284}] ~~~ title @s actionbar §a§lFuel§r: 30%
execute @s[scores={fuel=288}] ~~~ title @s actionbar §a§lFuel§r: 29%
execute @s[scores={fuel=292}] ~~~ title @s actionbar §a§lFuel§r: 28%
execute @s[scores={fuel=296}] ~~~ title @s actionbar §a§lFuel§r: 27%
execute @s[scores={fuel=300}] ~~~ title @s actionbar §a§lFuel§r: 26%
execute @s[scores={fuel=304}] ~~~ title @s actionbar §a§lFuel§r: 25%
execute @s[scores={fuel=308}] ~~~ title @s actionbar §a§lFuel§r: 24%
execute @s[scores={fuel=312}] ~~~ title @s actionbar §a§lFuel§r: 23%
execute @s[scores={fuel=316}] ~~~ title @s actionbar §a§lFuel§r: 22%
execute @s[scores={fuel=320}] ~~~ title @s actionbar §a§lFuel§r: 21%
execute @s[scores={fuel=324}] ~~~ title @s actionbar §a§lFuel§r: 20%
execute @s[scores={fuel=328}] ~~~ title @s actionbar §a§lFuel§r: 19%
execute @s[scores={fuel=332}] ~~~ title @s actionbar §a§lFuel§r: 18%
execute @s[scores={fuel=336}] ~~~ title @s actionbar §a§lFuel§r: 17%
execute @s[scores={fuel=340}] ~~~ title @s actionbar §a§lFuel§r: 16%
execute @s[scores={fuel=344}] ~~~ title @s actionbar §a§lFuel§r: §e15%
execute @s[scores={fuel=348}] ~~~ title @s actionbar §a§lFuel§r: §e14%
execute @s[scores={fuel=352}] ~~~ title @s actionbar §a§lFuel§r: §e13%
execute @s[scores={fuel=356}] ~~~ title @s actionbar §a§lFuel§r: §e12%
execute @s[scores={fuel=360}] ~~~ title @s actionbar §a§lFuel§r: §e11%
execute @s[scores={fuel=364}] ~~~ title @s actionbar §a§lFuel§r: §610%
execute @s[scores={fuel=368}] ~~~ title @s actionbar §a§lFuel§r: §69%
execute @s[scores={fuel=372}] ~~~ title @s actionbar §a§lFuel§r: §68%
execute @s[scores={fuel=376}] ~~~ title @s actionbar §a§lFuel§r: §67%
execute @s[scores={fuel=380}] ~~~ title @s actionbar §a§lFuel§r: §66%
execute @s[scores={fuel=384}] ~~~ title @s actionbar §a§lFuel§r: §45%
execute @s[scores={fuel=388}] ~~~ title @s actionbar §a§lFuel§r: §44%
execute @s[scores={fuel=392}] ~~~ title @s actionbar §a§lFuel§r: §43%
execute @s[scores={fuel=396}] ~~~ title @s actionbar §a§lFuel§r: §42%
execute @s[scores={fuel=400}] ~~~ title @s actionbar §a§lFuel§r: §41%
execute @s[scores={fuel=404}] ~~~ title @s actionbar §a§lFuel§r: §4Empty!
execute @s[scores={fuel=408}] ~~~ replaceitem entity @s slot.armor.chest 1 is:jetpack_empty
execute @s[scores={fuel=412}] ~~~ playsound random.break @s ~~~ 25
execute @s[scores={fuel=416}] ~~~ playsound beacon.deactivate @s ~~~ 0.4 0.5 
execute @s[scores={fuel=420}] ~~~ clear @s is:jetpack